# Generated by Django 2.0 on 2019-10-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninja',
            name='last_name',
            field=models.CharField(default='last', max_length=255),
            preserve_default=False,
        ),
    ]
