# Generated by Django 2.0 on 2019-10-11 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hogwarts',
            new_name='Users',
        ),
    ]
