# Generated by Django 2.0 on 2019-10-11 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191011_1158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Usersat',
        ),
    ]
